name: Build Kraftwerk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kraftwerk-${{ github.run_number }}
          path: build/libs/*-all.jar
          if-no-files-found: error

      # ↓↓↓ THIS IS THE PUBLISH PART ↓↓↓
      - name: Clone target repo
        run: |
          echo "Cloning target repo..."
          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/limettadev/uhc-gameserver.git target-repo

      - name: Copy built jar and commit
        run: |
          echo "Copying built jar..."
          cp build/libs/*-all.jar target-repo/plugins/Kraftwerk.jar
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugins/Kraftwerk.jar
          git commit -m "Update Kraftwerk.jar from build ${{ github.run_number }}" || echo "No changes to commit"
          git push
